### !CAUTION! ###
# Most cloud providers have a limit of 16 KB regarding the user-data that may be sent during VM creation.
# The result of this operating system config is exactly the user-data that will be sent to the providers.
# We must not exceed the 16 KB, so be careful when extending/changing anything in here.
### !CAUTION! ###
---
apiVersion: extensions.gardener.cloud/v1alpha1
kind: OperatingSystemConfig
metadata:
  name: {{ required "secretName is required" .Values.secretName }}-downloader
  namespace: {{ .Release.Namespace }}
  annotations:
    gardener.cloud/operation: reconcile
spec:
  type: {{ required "type is required" .Values.type }}
  purpose: {{ required "purpose is required" .Values.purpose }}
  units:
  - name: data-disk.service
    enable: true
    content: |
      [Unit]
      Description=Format Data Disk
      Before=local-fs-pre.target
      [Service]
      Type=oneshot
      RemainAfterExit=true
      ExecStart=/var/lib/data-disk/run.sh
  - name: var-lib.mount
    enable: true
    command: start
    content: |
      [Unit]
      Description=Mount Data disk to /var/lib
      Requires=data-disk.service
      After=data-disk.service
      Before=kubelet.service
      [Mount]
      What=/dev/disk/by-label/datadisk
      Where=/var/lib
      Type=xfs
      Options=defaults
      [Install]
      WantedBy=local-fs.target
  - name: cloud-config-downloader.service
    command: start
    enable: true
    content: |
      [Unit]
      Description=Downloads the actual cloud config from the Shoot API server and executes it
      After=docker.service docker.socket
      Wants=docker.socket
      [Service]
      Restart=always
      RestartSec=30
      EnvironmentFile=/etc/environment
      ExecStart=/var/lib/cloud-config-downloader/download-cloud-config.sh
  files:
  - path: /var/lib/data-disk/run.sh
    permissions: 0744
    content:
      inline:
        encoding: b64
        data: "IyEvYmluL3NoCkxBQkVMPWRhdGFkaXNrCmlmICEgYmxraWQgLS1sYWJlbCAkTEFCRUwgPiAvZGV2L251bGwgOyB0aGVuCiAgICBUQVJHRVRfRElTSz0kKGxzYmxrIC1kc25QIC1vIE5BTUUsUEFSVFRZUEUsRlNUWVBFIHwgZ3JlcCAnUEFSVFRZUEU9IiInIHwgZ3JlcCAnRlNUWVBFPSIiJyB8IGhlYWQgLW4xIHwgY3V0IC1mMiAtZFwiKQogICAgbWtmcy54ZnMgLUwgJExBQkVMICAvZGV2LyRUQVJHRVRfRElTSyAgIAogICAgbWtkaXIgL3RtcC9tIAogICAgbW91bnQgTEFCRUw9JExBQkVMIC90bXAvbQogICAgY3AgLWEgL3Zhci9saWIvKiAvdG1wL20vCiAgICB1bW91bnQgL3RtcC9tCmZpCg=="
  - path: /var/lib/cloud-config-downloader/credentials/server
    permissions: 0644
    content:
      inline:
        encoding: b64
        data: {{ .Values.server | b64enc }}
  - path: /var/lib/cloud-config-downloader/credentials/ca.crt
    permissions: 0644
    content:
      secretRef:
        name: cloud-config-downloader
        dataKey: ca.crt
  - path: /var/lib/cloud-config-downloader/credentials/client.crt
    permissions: 0644
    content:
      secretRef:
        name: cloud-config-downloader
        dataKey: cloud-config-downloader.crt
  - path: /var/lib/cloud-config-downloader/credentials/client.key
    permissions: 0644
    content:
      secretRef:
        name: cloud-config-downloader
        dataKey: cloud-config-downloader.key
  - path: /var/lib/cloud-config-downloader/download-cloud-config.sh
    permissions: 0744
    content:
      inline:
        encoding: b64
        data: {{ include "seed-operatingsystemconfig.downloader.download-script" . | b64enc }}
